"""Master-reference image generation.

This is the ONE place in the pipeline that calls `/v1/images/generations`
(pure generation, no reference image). Every other call uses
`/v1/images/edits` with the master-reference attached as the style
anchor.

The reference is regenerated by `make sprites-reference` only —
`make sprites` MUST never touch `master-reference.png`. The image is
committed alongside `world.md` as a binary; it changes only with a
deliberate `make sprites-reference` invocation and PR review.
"""

from __future__ import annotations

import base64
import os
from io import BytesIO

import httpx
from PIL import Image


# Per design.md §D2 + Open Questions §Q1: single-building reference
# (a canonical half-timber house) anchors the style register. Per the
# spike data, single-building references already produce strong
# inter-sprite cohesion; the multi-building variant adds complexity
# without measurable benefit.
SINGLE_BUILDING_PROMPT_SUFFIX = (
    "Generate a single 2:1 isometric pixel-art sprite of one "
    "half-timber-and-plaster medieval coastal-town house: two storeys, "
    "steep terracotta roof, one south-facing window with mullions, one "
    "south-facing wooden door, vertical-stud half-timber framing on a "
    "light-plaster wall. The building stands on a SMALL DIAMOND "
    "footprint of grass — just enough grass to anchor the silhouette, "
    "not a full landscape. EVERYTHING ELSE IS TRANSPARENT (alpha=0). "
    "Do NOT paint a background; do NOT extend the grass beyond the "
    "diamond footprint. The API is called with "
    "`background: \"transparent\"` and the result MUST be a PNG with "
    "per-pixel alpha. Crisp pixel edges, no anti-aliasing, no "
    "gradients, no text. Outline weight: one canonical pixel of dark "
    "`#1A1410` on south and east edges. This image is the STYLE "
    "ANCHOR — every subsequent sprite in this game is generated with "
    "this image attached as a reference, so its palette, outline, "
    "pixel grain, and silhouette register MUST embody the visual "
    "identity declared above."
)


def _api_url() -> str:
    base = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com")
    return base.rstrip("/") + "/v1/images/generations"


def build_reference_prompt(world_md: str) -> str:
    """Compose the prompt for the master-reference call. Includes
    world.md verbatim plus the canonical single-building suffix."""
    return (
        "=== WORLD STYLE BIBLE ===\n"
        f"{world_md.strip()}\n\n"
        "=== INSTRUCTIONS ===\n"
        f"{SINGLE_BUILDING_PROMPT_SUFFIX}\n"
    )


def generate_master_reference(
    world_md: str,
    model_id: str,
    size: str = "1024x1024",
    timeout: float = 300.0,
) -> Image.Image:
    """Call `/v1/images/generations` and return the resulting Pillow
    image. Requires `OPENAI_API_KEY` in the environment.

    The caller is responsible for writing the image to disk.
    """
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError(
            "OPENAI_API_KEY is not set in the environment — required "
            "for master-reference generation"
        )
    prompt = build_reference_prompt(world_md)
    payload = {
        "model": model_id,
        "prompt": prompt,
        "size": size,
        "n": 1,
        # Real per-pixel alpha out of the model. The post-process step
        # in batcher.py thresholds the soft alpha to binary 0/255 so
        # pixel-art edges stay crisp after the downsample pass.
        "background": "transparent",
        "output_format": "png",
    }
    headers = {"Authorization": f"Bearer {api_key}"}
    with httpx.Client(timeout=timeout) as client:
        resp = client.post(_api_url(), json=payload, headers=headers)
        if resp.status_code >= 400:
            raise RuntimeError(
                f"image generation failed: {resp.status_code} {resp.text[:500]}"
            )
        data = resp.json()
    item = data["data"][0]
    if "b64_json" in item and item["b64_json"]:
        raw = base64.b64decode(item["b64_json"])
        return Image.open(BytesIO(raw)).convert("RGBA")
    if "url" in item and item["url"]:
        with httpx.Client(timeout=timeout) as client:
            blob = client.get(item["url"])
            blob.raise_for_status()
        return Image.open(BytesIO(blob.content)).convert("RGBA")
    raise RuntimeError(f"unexpected response shape: {list(item.keys())}")
